chore: move repo to loopbackio org
loopbackio/strong-soap pull request #322
Opened 2021-07-14 01:10 UTC by dhmlau

As part of https://github.com/strongloop/loopback-next/issues/7595

I've switched the contribution method for this repo from CLA to DCO. I probably have missed this repo when I was enabling DCO for most of the LoopBack repos.

Signed-off-by: Diana Lau <dhmlau@ca.ibm.com>

### Description

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2021-07-14 04:42 UTC, marioestradarosa approved these changes

2021-07-14 05:37 UTC, achrinza approved these changes

2021-07-14 05:40 UTC, achrinza requested changes
Same issue raised by https://github.com/loopbackio/strong-error-handler/pull/92#discussion_r669277100:

> Thank you for your interest in `strong-soap`, an open source project
administered by StrongLoop.

2021-07-27 04:02 UTC, achrinza approved these changes

2021-07-27 17:48 UTC, merged